# Foundations: NumPy
## NumPy Array

In [1]:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

In [2]:
[[i + 1 for i in row] for row in matrix]

[[2, 3, 4], [5, 6, 7], [8, 9, 10]]

In [3]:
# First, let's import NumPy
import numpy as np

In [4]:
# Constructing an array with a simple list results in a 1d array
array1 = np.array([10, 100, 1000.])

In [5]:
# Constructing an array with a nested list results in a 2d array
array2 = np.array([[1., 2., 3.],
                   [4., 5., 6.]])

In [6]:
array1.dtype

dtype('float64')

In [7]:
float(array1[0])

10.0

## Vectorization and Broadcasting

In [8]:
array2 + 1

array([[2., 3., 4.],
       [5., 6., 7.]])

In [9]:
array2 * array2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [10]:
array2 * array1

array([[  10.,  200., 3000.],
       [  40.,  500., 6000.]])

In [11]:
array2 @ array2.T  # array2.T is a shortcut for array2.transpose()

array([[14., 32.],
       [32., 77.]])

## Universal Functions (ufunc)

In [12]:
import math

In [13]:
math.sqrt(array2)  # This will raise en Error

TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
np.array([[math.sqrt(i) for i in row] for row in array2])

In [ ]:
np.sqrt(array2)

In [ ]:
array2.sum(axis=0)  # Returns a 1d array

In [14]:
array2.sum()

21.0

## Getting and Setting Array Elements

In [ ]:
array1[2]  # Returns a scalar

In [ ]:
array2[0, 0]  # Returns a scalar

In [ ]:
array2[:, 1:]  # Returns a 2d array

In [ ]:
array2[:, 1]  # Returns a 1d array

In [ ]:
array2[1, :2]  # Returns a 1d array

## Useful Array Constructors

In [ ]:
np.arange(2 * 5).reshape(2, 5)  # 2 rows, 5 columns

In [ ]:
np.random.randn(2, 3)  # 2 rows, 3 columns

## View vs. Copy

In [ ]:
array2

In [ ]:
subset = array2[:, :2]
subset

In [ ]:
subset[0, 0] = 1000

In [ ]:
subset

In [ ]:
array2